export const actionTypes = {
    FETCHING_START:"FETCHING START",
    FETCHING_SUCCESS:"FETCHING SUCCESS",
    FETCHING_ERROR: "FETCHING ERROR",
    ADD_TO_CART: "ADD TO CART",
    ADD_TO_WISHLIST: "ADD TO WISHLIST"
}